runtime: python38

entrypoint: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker

instance_class: F2

env_variables:
  ENVIRONMENT: "PRODUCTION"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto