name: Deploy to Google App Engine

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GAE_DEPLOY_KEY }}
          deliverables:
            app.yaml
